### ISSUE TITLE
With latest cacti-1.2.X_beta it is impossible to use rrdproxy with rrdcached enabled.

### ISSUE THREAD

**Issue by pornmailbox** [Cacti/rrdproxy#4]
cacti debug log indicates:
.....
cacti BOOST RRDP: ERROR: The caching daemon cannot be used together with templates and skip-past-updates yet.
.....

only after disabling in config "/usr/bin/rrdcached/", it starts to process non-empty graphs.

**Comment by browniebraun** [comment]
This is not a bug in RRDproxy. However, I have to thank you for bringing that up.
Looks like Tobi does / will not implement this useful feature in combination with templates in the RRDcached daemon.  :/  Not sure, if there are issues why he can not do that.

**Comment by pornmailbox** [comment]
https://github.com/Cacti/cacti/issues/2054 - This was the firs attempt to resolve this issue.

**Comment by netniV** [comment]
The fix I did there was due to an extra parameter used on a define which PHP 7.3 doesn't like.  However, that was not a fix for any issue on RRDproxy/RRDcached issue.

**Comment by pornmailbox** [comment]
ok. but I'm only investigate that the latest cacti version doesn't work correctly with rrdproxy with enabled "rrdcached". I can't correctly relate this bug to a cacti server or rrdproxy server...

**Comment by browniebraun** [comment]
Flag --skip-past-updates will be set in Cacti 1.2 in file /lib/boost.php depending on having RRDtool 1.5 or above installed, which absolutely makes sense. Maybe we should disable it if storage_location is set to the proxy until Tobi will support it in combination with templates. I hope he will.

**Comment by netniV** [comment]
Yeah, that may be something until @oetiker can support it.  I've tagged him here, so hopefully he will be able to weigh in and say.  The thing is, even that may take some time to reach distro's via packages.  I made a mod a few months back too rrdtool to allow it to have multiple line titles, and that's not main stream yet.

**Comment by oetiker** [comment]
@netniV I am not aware of what RRDproxy does exactly, but note that rrdcached has some severe design issues when it comes to directly replace rrdtool. especially all cases where you access the data cannot be optimized with the approach rrdcached takes. There has been some interest in creating a new remote interface around https://developers.google.com/protocol-buffers/ which would cache before writing to disk and not before processing the data.

**Comment by netniV** [comment]
Thanks for getting back to us, @oetiker. RRDproxy basically allows you to have the RRD files on a separate server to the Cacti instance:
https://github.com/cacti/rrdproxy/

The idea of the remote interface using the protocol-buffers sounds interesting, and I'm sure @browniebraun who is the main author, will probably offer his thoughts about it.

**Comment by browniebraun** [comment]
Well, the idea behind RRDproxy is to place the RRDfiles wherever you want. This separation makes it easier to have servers offering a high I/O performance while using less powerfull devices for the rest of Cacti. Once completed ( hopefully by the end of this week), version 1.2 will also allow to build up Master-Master as well as Master-Slave setups where the nodes will replicate each other. This makes the complete backup topic easier. (1.2 also introduces much more CLI commands and debugging features)

RRDcached itself is in combination with Cacti not required, because it is more a cache behind a cache and as you know Cacti devs are preferring Boost. So far I haven't had any time to compare the performance of having RRDcached being enabled or not. Running in my environment with more 2700 hosts and around 150.000 RRDs I do not directly notice a difference. 
While Cacti will learn concurrent Boost updates soon, I have that already running, with 1.3 support of Net-SNMP as well as structured bulk updates will follow. The latter one will reduce the encryption overhead.
Currently it takes around 7 minutes to write 18 million records down to these files using 8 concurrrent streams.

**Comment by browniebraun** [comment]
Now the wizard supports to leave the RRDcached function disabled, which is recommended. In combination with Cacti Boost enabling the embedded RRDtool RRDcache does not deliver any kind of performance increase.
